WIP

diff --git a/roles/apache/tasks/virtual_hosts.yml b/roles/apache/tasks/virtual_hosts.yml
--- a/roles/apache/tasks/virtual_hosts.yml
+++ b/roles/apache/tasks/virtual_hosts.yml
@@ -1,18 +1,6 @@
 # SPDX-License-Identifier: MIT-0
 ---
-- name: Create document root directories for virtual hosts
-  ansible.builtin.file:
-    path: "{{ item.document_root }}"
-    state: directory
-    owner: www-data
-    group: www-data
-    mode: "0755"
-  loop: "{{ apache_virtual_hosts }}"
-  when:
-    - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'present'
-
-- name: Create virtual host configuration files
+- name: Create HTTP virtual host configuration files
   ansible.builtin.template:
     src: vhost.conf.j2
     dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
@@ -22,8 +10,117 @@
   loop: "{{ apache_virtual_hosts }}"
   when:
     - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'present'
+    - item.http is defined
   notify: Reload apache
+
+- name: Create HTTPS virtual host configuration files
+  ansible.builtin.template:
+    src: vhost-ssl.conf.j2
+    dest: "/etc/apache2/sites-available/{{ item.name }}-ssl.conf"
+    owner: root
+    group: root
+    mode: "0644"
+  loop: "{{ apache_virtual_hosts }}"
+  when:
+    - apache_virtual_hosts | length > 0
+    - item.https is defined
+  notify: Reload apache
+
+- name: Create document root directories for virtual hosts
+  ansible.builtin.shell: |
+    set -o pipefail
+    source /etc/apache2/envvars
+    {% for envvar in apache_envvars | default([]) %}
+    export {{ envvar.name }}="{{ envvar.value }}"
+    {% endfor %}
+    path=$(echo "{{ item.document_root }}" | envsubst)
+    mkdir -p "$path"
+  args:
+    executable: /bin/bash
+  loop: "{{ apache_virtual_hosts }}"
+  when:
+    - apache_virtual_hosts | length > 0
+  changed_when: false
+
+- name: Create HTTP error log directories for virtual hosts
+  ansible.builtin.shell: |
+    set -o pipefail
+    source /etc/apache2/envvars
+    {% for envvar in apache_envvars | default([]) %}
+    export {{ envvar.name }}="{{ envvar.value }}"
+    {% endfor %}
+    logpath=$(echo "{{ item.http.error_log }}" | envsubst)
+    logdir=$(dirname "$logpath")
+    mkdir -p "$logdir"
+    echo "$logdir"
+  args:
+    executable: /bin/bash
+  loop: "{{ apache_virtual_hosts }}"
+  when:
+    - apache_virtual_hosts | length > 0
+    - item.http is defined
+    - item.http.error_log is defined
+  changed_when: false
+
+- name: Create HTTP custom log directories for virtual hosts
+  ansible.builtin.shell: |
+    set -o pipefail
+    source /etc/apache2/envvars
+    {% for envvar in apache_envvars | default([]) %}
+    export {{ envvar.name }}="{{ envvar.value }}"
+    {% endfor %}
+    logpath=$(echo "{{ item.http.access_log }}" | envsubst | awk '{print $1}')
+    logdir=$(dirname "$logpath")
+    mkdir -p "$logdir"
+    echo "$logdir"
+  args:
+    executable: /bin/bash
+  loop: "{{ apache_virtual_hosts }}"
+  when:
+    - apache_virtual_hosts | length > 0
+    - item.http is defined
+    - item.http.access_log is defined
+  changed_when: false
+
+- name: Create HTTPS error log directories for virtual hosts
+  ansible.builtin.shell: |
+    set -o pipefail
+    source /etc/apache2/envvars
+    {% for envvar in apache_envvars | default([]) %}
+    export {{ envvar.name }}="{{ envvar.value }}"
+    {% endfor %}
+    logpath=$(echo "{{ item.https.error_log }}" | envsubst)
+    logdir=$(dirname "$logpath")
+    mkdir -p "$logdir"
+    echo "$logdir"
+  args:
+    executable: /bin/bash
+  loop: "{{ apache_virtual_hosts }}"
+  when:
+    - apache_virtual_hosts | length > 0
+    - item.https is defined
+    - item.https.error_log is defined
+  changed_when: false
+
+- name: Create HTTPS custom log directories for virtual hosts
+  ansible.builtin.shell: |
+    set -o pipefail
+    source /etc/apache2/envvars
+    {% for envvar in apache_envvars | default([]) %}
+    export {{ envvar.name }}="{{ envvar.value }}"
+    {% endfor %}
+    logpath=$(echo "{{ item.https.access_log }}" | envsubst | awk '{print $1}')
+    logdir=$(dirname "$logpath")
+    mkdir -p "$logdir"
+    echo "$logdir"
+  args:
+    executable: /bin/bash
+  loop: "{{ apache_virtual_hosts }}"
+  when:
+    - apache_virtual_hosts | length > 0
+    - item.https is defined
+    - item.https.access_log is defined
+  changed_when: false
 
 - name: Enable HTTP virtual hosts
   ansible.builtin.command:
@@ -33,7 +130,6 @@
   loop: "{{ apache_virtual_hosts }}"
   when:
     - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'present'
     - item.http is defined
     - item.http.enabled | default(true)
   notify: Reload apache
@@ -48,27 +144,25 @@
   loop: "{{ apache_virtual_hosts }}"
   when:
     - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'present'
     - item.http is defined
     - not (item.http.enabled | default(true))
   notify: Reload apache
 
 - name: Enable HTTPS virtual hosts
   ansible.builtin.command:
-    cmd: "a2ensite {{ item.name }}"
+    cmd: "a2ensite {{ item.name }}-ssl"
   register: apache_enable_https_vhost_result
   changed_when: "'Enabling site' in apache_enable_https_vhost_result.stdout"
   loop: "{{ apache_virtual_hosts }}"
   when:
     - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'present'
     - item.https is defined
     - item.https.enabled | default(true)
   notify: Reload apache
 
 - name: Disable HTTPS virtual hosts
   ansible.builtin.command:
-    cmd: "a2dissite {{ item.name }}"
+    cmd: "a2dissite {{ item.name }}-ssl"
   register: apache_disable_https_vhost_result
   changed_when:
     - "'Site' in apache_disable_https_vhost_result.stdout"
@@ -76,17 +170,6 @@
   loop: "{{ apache_virtual_hosts }}"
   when:
     - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'present'
     - item.https is defined
     - not (item.https.enabled | default(true))
-  notify: Reload apache
-
-- name: Remove virtual host configuration files
-  ansible.builtin.file:
-    path: "/etc/apache2/sites-available/{{ item.name }}.conf"
-    state: absent
-  loop: "{{ apache_virtual_hosts }}"
-  when:
-    - apache_virtual_hosts | length > 0
-    - item.state | default('present') == 'absent'
   notify: Reload apache
